package com.rga.estimator2;

public enum Positions {
	BO_ASSOCIATE_PRODUCER("Associate Producer") ,
	BO_BUSINESS_STRATEGY_ASSOCIATE("Business Strategy Associate") ,
	BO_CHIEF_SCIENTIST ("Chief Scientist+") ,
	BO_DIRECTOR_OF_NETWORK_DEVELOPMENT("Director of Network Development") ,
	BO_DIRECTOR_OF_NETWORK_DEVELOPMENT_RGA_VENTURES("Director of Network Development, R/GA Ventures") ,
	BO_DIRECTOR_BUSINESS_OPERATIONS ("Director, Business Operations+") ,
	BO_DIRECTOR_NEW_PROGRAMS_DEVELOPMENT("Director, New Programs Development") ,
	BO_DIRECTOR_NEW_PROGRAMS_DEVELOPMENT_RGA_VENTURES("Director, New Programs Development, R/GA Ventures") ,
	BO_MANAGER_BUSINESS_OPERATIONS("Manager, Business Operations") ,
	BO_MANAGING_DIRECTOR_BUSINESS_OPERATIONS ("Managing Director, Business Operations+") ,
	BO_MANAGING_DIRECTOR_DODGERS_ACCELERATOR("Managing Director, Dodgers Accelerator") ,
	BO_MD_FOUNDER_ENGAGEMENT_GLOBAL_SPORTS_VENTURE_STUDIO("MD Founder Engagement Global Sports Venture Studio") ,
	BO_OPERATIONS_ASSOCIATE("Operations Associate") ,
	BO_PORTFOLIO_MANAGER_ASSOCIATE_STRATEGIST("Portfolio Manager/Associate Strategist") ,
	BO_PRODUCER("Producer") ,
	BO_PRODUCT_MANAGER_TECHNICAL_PROJECT_MANAGER ("Product Manager/Technical Project Manager+") ,
	BO_PROGRAM_COORDINATOR_RGA_ACCELERATOR("Program Coordinator, R/GA Accelerator") ,
	BO_PROGRAM_COORDINATOR_RGA_VENTURES("Program Coordinator, R/GA Ventures") ,
	BO_PROGRAM_DIRECTOR_RGA_ACCELERATOR("Program Director, R/GA Accelerator") ,
	BO_PROGRAM_DIRECTOR_RGA_VENTURES("Program Director, R/GA Ventures") ,
	BO_PROGRAM_MANAGER_RGA_ACCELERATOR("Program Manager, R/GA Accelerator") ,
	BO_PROGRAM_MANAGER_RGA_VENTURES("Program Manager, R/GA Ventures") ,
	BO_REPORTER_MANAGER ("Reporter Manager+") ,
	BO_SENIOR_DIRECTOR_OF_PROGRAMS_RGA_VENTURES("Senior Director of Programs, R/GA Ventures") ,
	BO_SENIOR_MANAGER_BUSINESS_OPERATIONS ("Senior Manager, Business Operations+") ,
	BO_SENIOR_MANAGER_COMMUNICATIONS_AND_EVENTS("Senior Manager, Communications and Events") ,
	BO_SENIOR_OPERATIONS_MANAGER_RGA_VENTURES("Senior Operations Manager, R/GA Ventures") ,
	BO_SENIOR_QA_ENGINEER("Senior QA Engineer") ,
	BO_SENIOR_SOFTWARE_ENGINEER ("Senior Software Engineer+") ,
	BO_VP_PARTNER_RGA_VENTURES("VP, Partner, R/GA Ventures") ,
	BT_APPRENTICE_BUSINESS_TRANSFORMATION("Apprentice, Business Transformation") ,
	BT_ART_DIRECTOR("Art Director") ,
	BT_ASSOCIATE_CREATIVE_DIRECTOR("Associate Creative Director") ,
	BT_ASSOCIATE_DIRECTOR("Associate Director") ,
	BT_ASSOCIATE_DIRECTOR_BRAND("Associate Director, Brand") ,
	BT_ASSOCIATE_PRODUCER("Associate Producer") ,
	BT_ASSOCIATE_VERBAL_DESIGN_DIRECTOR("Associate Verbal Design Director") ,
	BT_ASSOCIATE_ANALYST("Associate/Analyst") ,
	BT_CLIENT_PARTNER_BUSINESS_TRANSFORMATION("Client Partner, Business Transformation") ,
	BT_CONSULTANT("Consultant") ,
	BT_CREATIVE_DIRECTOR("Creative Director") ,
	BT_DESIGN_DIRECTOR("Design Director") ,
	BT_DESIGNER("Designer") ,
	BT_DIRECTOR_BUSINESS_TRANSFORMATION("Director, Business Transformation") ,
	BT_DIRECTOR_SOFTWARE_PLATFORM_LAB_PARTNERSHIPS("Director, Software Platform Lab Partnerships") ,
	BT_ENGAGEMENT_MANAGER_BUSINESS_TRANSFORMATION("Engagement Manager, Business Transformation") ,
	BT_EVP_BUSINESS_TRANSFORMATION("EVP, Business Transformation") ,
	BT_EXECUTIVE_CREATIVE_DIRECTOR("Executive Creative Director") ,
	BT_EXECUTIVE_DIRECTOR_BUSINESS_TRANSFORMATION("Executive Director, Business Transformation") ,
	BT_EXECUTIVE_PRODUCER("Executive Producer") ,
	BT_GROUP_CREATIVE_DIRECTOR("Group Creative Director") ,
	BT_GROUP_DIRECTOR_OF_BUSINESS_TRANSFORMATION("Group Director of Business Transformation") ,
	BT_GROUP_DIRECTOR_EXECUTIVE_CREATIVE_DIRECTOR("Group Director, Executive Creative Director") ,
	BT_GROUP_STRATEGY_LEAD("Group Strategy Lead") ,
	BT_INTERN_BUSINESS_TRANSFORMATION("Intern, Business Transformation") ,
	BT_MANAGING_DIRECTOR_BUSINESS_TRANSFORMATION("Managing Director, Business Transformation") ,
	BT_PARTNERSHIPS_ASSOCIATE_SPL("Partnerships Associate, SPL") ,
	BT_PRODUCER("Producer") ,
	BT_SENIOR_CONSULTANT("Senior Consultant") ,
	BT_SENIOR_DESIGNER("Senior Designer") ,
	BT_SENIOR_PRODUCER("Senior Producer") ,
	BT_SENIOR_STRATEGIST("Senior Strategist") ,
	BT_SENIOR_VERBAL_DESIGNER("Senior Verbal Designer") ,
	BT_SENIOR_VISUAL_DESIGNER("Senior Visual Designer") ,
	BT_STRATEGY_DIRECTOR("Strategy Director") ,
	BT_SVP_BUSINESS_TRANSFORMATION("SVP, Business Transformation") ,
	BT_VERBAL_DESIGNER("Verbal Designer") ,
	BT_VP_BUSINESS_INTELLIGENCE("VP, Business Intelligence") ,
	BT_VP_EXECUTIVE_CREATIVE_DIRECTOR("VP, Executive Creative Director") ,
	BT_VP_MANAGING_DIRECTOR_BUSINESS_CONSULTING("VP, Managing Director, Business Consulting") ,
	CS_EXECUTIVE_CLIENT_SERVICES_DIRECTOR("Executive Client Services Director") ,
	CS_CLIENT_SERVICES_DIRECTOR("Client Services Director") ,
	CS_ACCOUNT_DIRECTOR("Account Director") ,
	CS_ACCOUNT_COORDINATOR("Account Coordinator") ,
	CS_ACCOUNT_EXECUTIVE("Account Executive") ,
	CS_ACCOUNT_MANAGER("Account Manager") ,
	CS_ACCOUNT_SUPERVISOR("Account Supervisor") ,
	CS_APPRENTICE_CLIENT_SERVICES("Apprentice, Client Services") ,
	CS_ASSOCIATE_ACCOUNT_DIRECTOR("Associate Account Director") ,
	CS_ASSOCIATE_DIRECTOR_BUSINESS_DEVELOPMENT("Associate Director, Business Development") ,
	CS_ASSOCIATE_MARKETING_DIRECTOR("Associate Marketing Director") ,
	CS_ASSOCIATE_MARKETING_MANAGER("Associate Marketing Manager") ,
	CS_BUSINESS_DEVELOPMENT_DIRECTOR("Business Development Director") ,
	CS_EXECUTIVE_MARKETING_DIRECTOR("Executive Marketing Director") ,
	CS_GLOBAL_ACCOUNT_DIRECTOR("Global Account Director") ,
	CS_GLOBAL_CLIENT_SERVICES_DIRECTOR("Global Client Services Director") ,
	CS_GLOBAL_GROUP_ACCOUNT_DIRECTOR("Global Group Account Director") ,
	CS_GLOBAL_GROUP_MARKETING_DIRECTOR("Global Group Marketing Director") ,
	CS_GROUP_ACCOUNT_DIRECTOR("Group Account Director") ,
	CS_GROUP_DIRECTOR_CLIENT_SERVICES("Group Director, Client Services") ,
	CS_GROUP_MARKETING_DIRECTOR("Group Marketing Director") ,
	CS_INTERN_CLIENT_SERVICES("Intern, Client Services") ,
	CS_INTERN_MARKETING("Intern, Marketing") ,
	CS_MANAGEMENT_SUPERVISOR("Management Supervisor") ,
	CS_MANAGING_DIRECTOR_CLIENT_SERVICES("Managing Director, Client Services") ,
	CS_MARKETING_DIRECTOR("Marketing Director") ,
	CS_MARKETING_MANAGER("Marketing Manager") ,
	CS_REGIONAL_CLIENT_SERVICES_DIRECTOR("Regional Client Services Director") ,
	CS_SENIOR_ACCOUNT_DIRECTOR("Senior Account Director") ,
	CS_SENIOR_ACCOUNT_EXECUTIVE("Senior Account Executive") ,
	CS_SENIOR_MARKETING_DIRECTOR("Senior Marketing Director") ,
	CS_SENIOR_MARKETING_MANAGER("Senior Marketing Manager") ,
	CS_VP_MD_CRM("VP MD, CRM") ,
	CS_VP_CLIENT_SERVICES("VP, Client Services") ,
	CS_VP_CONTENT_AND_PARTNERSHIPS("VP, Content and Partnerships") ,
	CS_VP_EXECUTIVE_MARKETING_DIRECTOR("VP, Executive Marketing Director") ,
	CS_VP_MANAGING_DIRECTOR_CLIENT_SERVICES("VP, Managing Director, Client Services") ,
	COMM_MANAGING_EDITOR_FUTUREVISION("Managing Editor, Futurevision") ,
	COMM_SENIOR_MANAGER_CORPORATE_COMMUNICATIONS("Senior Manager, Corporate Communications") ,
	CONT_EXECUTIVE_CONTENT_PRODUCER("Executive Content Producer") ,
	CONT_EXECUTIVE_PRODUCER_POST_PRODUCTION__CG_MOTION("Executive Producer, Post-Production & CG/Motion") ,
	CONT_SENIOR_CONTENT_PRODUCER("Senior Content Producer") ,
	CONT_SENIOR_PRODUCER_CS("Senior Producer CS") ,
	CONT_SENIOR_VIDEO_EDITOR("Senior Video Editor") ,
	CONT_VIDEO_EDITOR("Video Editor") ,
	CONT_PRODUCER("Producer") ,
	CONT_ASSOCIATE_PRODUCER("Associate Producer") ,
	CONT_3D_ART_DIRECTOR("3D Art Director") ,
	CONT_3D_ARTIST("3D Artist") ,
	CONT_ANIMATION_LEAD("Animation Lead") ,
	CONT_ANIMATOR("Animator") ,
	CONT_ART_DIRECTOR("Art Director") ,
	CONT_ASSOCIATE_CONTENT_PRODUCER("Associate Content Producer") ,
	CONT_ASSOCIATE_CREATIVE_DIRECTOR("Associate Creative Director") ,
	CONT_ASSOCIATE_DIRECTOR_CONTENT_EDITOR("Associate Director, Content Editor") ,
	CONT_ASSOCIATE_STRATEGY_DIRECTOR("Associate Strategy Director") ,
	CONT_ASSOCIATE_VIDEO_EDITOR("Associate Video Editor") ,
	CONT_ASSOCIATE_BUSINESS_AFFAIRS("Associate, Business Affairs") ,
	CONT_CONTENT_CREATOR("Content Creator") ,
	CONT_CONTENT_PRODUCER("Content Producer") ,
	CONT_CONTENT_PRODUCER_ART("Content Producer, Art") ,
	CONT_CONTENT_PRODUCER_CG_MOTION("Content Producer, CG/Motion") ,
	CONT_CONTENT_PRODUCER_PRINT("Content Producer, Print") ,
	CONT_COORDINATOR_BUSINESS_AFFAIRS("Coordinator, Business Affairs") ,
	CONT_CREATIVE_DIRECTOR("Creative Director") ,
	CONT_CREATIVE_DIRECTOR__SENIOR_TECHNICAL_DIRECTOR("Creative Director & Senior Technical Director") ,
	CONT_CREATIVE_PRODUCTION_ASSOCIATE("Creative Production Associate") ,
	CONT_DESIGN_DIRECTOR_CG_MOTION("Design Director, CG/Motion") ,
	CONT_DIRECTOR_BUSINESS_AFFAIRS("Director, Business Affairs") ,
	CONT_DIRECTOR_CONTENT_PRODUCTION_PRINT("Director, Content Production, Print") ,
	CONT_DIRECTOR_POST_PRODUCTION("Director, Post-Production") ,
	CONT_EXECUTIVE_CONTENT_PRODUCER_ART("Executive Content Producer, Art") ,
	CONT_EXECUTIVE_CREATIVE_DIRECTOR("Executive Creative Director") ,
	CONT_EXECUTIVE_CREATIVE_DIRECTOR__DIRECTOR_CG_MOTION("Executive Creative Director & Director, CG/Motion") ,
	CONT_EXECUTIVE_DIRECTOR_CONTENT("Executive Director, Content") ,
	CONT_EXECUTIVE_PRODUCER("Executive Producer") ,
	CONT_EXECUTIVE_PRODUCER_ART_PRODUCTION("Executive Producer, Art Production") ,
	CONT_EXECUTIVE_PRODUCTION_DIRECTOR_CONTENT_STUDIO("Executive Production Director, Content Studio") ,
	CONT_GROUP_DIRECTOR_CONTENT_PRODUCTION("Group Director, Content Production") ,
	CONT_INTERN_CONTENT_STUDIO("Intern, Content Studio") ,
	CONT_MANAGER_BUSINESS_AFFAIRS("Manager, Business Affairs") ,
	CONT_MECHANICAL_ARTIST("Mechanical Artist") ,
	CONT_MOTION_DESIGN_DIRECTOR("Motion Design Director") ,
	CONT_MOTION_GRAPHICS_DESIGNER("Motion Graphics Designer") ,
	CONT_PRODUCTION_ASSISTANT("Production Assistant") ,
	CONT_PRODUCTION_COORDINATOR("Production Coordinator") ,
	CONT_PRODUCTION_MANAGER_LIVE_ACTION("Production Manager, Live Action") ,
	CONT_SENIOR_3D_ARTIST("Senior 3D Artist") ,
	CONT_SENIOR_ANIMATOR("Senior Animator") ,
	CONT_SENIOR_CONTENT_PRODUCER_ART("Senior Content Producer, Art") ,
	CONT_SENIOR_CONTENT_PRODUCER_PRINT("Senior Content Producer, Print") ,
	CONT_SENIOR_COPYWRITER("Senior Copywriter") ,
	CONT_SENIOR_MANAGER_BUSINESS_AFFAIRS("Senior Manager, Business Affairs") ,
	CONT_SENIOR_MECHANICAL_ARTIST("Senior Mechanical Artist") ,
	CONT_SENIOR_MOTION_DESIGNER("Senior Motion Designer") ,
	CONT_SENIOR_SOUND_DESIGNER("Senior Sound Designer") ,
	CONT_SENIOR_TALENT_LEAD_CREATOR_STUDIO("Senior Talent Lead, Creator Studio") ,
	CONT_SOUND_DESIGNER("Sound Designer") ,
	CONT_STUDIO_MANAGER("Studio Manager") ,
	CONT_TALENT_LEAD_CREATOR_STUDIO("Talent Lead, Creator Studio") ,
	CONT_VP_MANAGING_DIRECTOR("VP, Managing Director") ,
	CONT_APPRENTICE_CONTENT_STUDIO("Apprentice, Content Studio") ,
	CONT_ASSOCIATE_CREATIVE_DIRECTOR_POST_PRODUCTION("Associate Creative Director, Post Production") ,
	CONT_ASSOCIATE_DIRECTOR_CONTENT_CREATOR("Associate Director, Content Creator") ,
	CONT_CONTENT_PRODUCER_POST_PRODUCTION("Content Producer, Post Production") ,
	CONT_DIRECTOR_CONTENT_PRODUCTION("Director, Content Production") ,
	CONT_EXECUTIVE_DIRECTOR_RGA_STUDIOS_US_OPERATIONS("Executive Director, R/GA Studios, US Operations") ,
	CONT_JUNIOR_VIDEO_EDITOR("Junior Video Editor") ,
	CONT_MANAGING_DIRECTOR_CONTENT_STUDIO("Managing Director, Content Studio") ,
	CONT_SENIOR_ART_DIRECTOR("Senior Art Director") ,
	CONT_SENIOR_CONTENT_CREATOR("Senior Content Creator") ,
	COPY_CREATIVE_DIRECTOR("Creative Director") ,
	COPY_ASSOCIATE_CREATIVE_DIRECTOR("Associate Creative Director") ,
	COPY_COPYWRITER("Copywriter") ,
	COPY_JUNIOR_COPYWRITER("Junior Copywriter") ,
	COPY_APPRENTICE_COPYWRITING("Apprentice, Copywriting") ,
	COPY_ASSOCIATE_CREATIVE_DIRECTOR_SOCIAL("Associate Creative Director, Social") ,
	COPY_ASSOCIATE_DIRECTOR_CONTENT_STRATEGY("Associate Director, Content Strategy") ,
	COPY_CONTENT_STRATEGIST("Content Strategist") ,
	COPY_CONTENT_STRATEGY_DIRECTOR("Content Strategy Director") ,
	COPY_COPY_DIRECTOR("Copy Director") ,
	COPY_EXECUTIVE_CREATIVE_DIRECTOR("Executive Creative Director") ,
	COPY_EXECUTIVE_CREATIVE_DIRECTOR_OF_SOCIAL("Executive Creative Director of Social") ,
	COPY_GROUP_CREATIVE_DIRECTOR("Group Creative Director") ,
	COPY_GROUP_EXECUTIVE_CREATIVE_DIRECTOR("Group Executive Creative Director") ,
	COPY_INTERN_COPY("Intern, Copy") ,
	COPY_PROOFREADER("Proofreader") ,
	COPY_SENIOR_CONTENT_STRATEGIST("Senior Content Strategist") ,
	COPY_SENIOR_COPYWRITER("Senior Copywriter") ,
	COPY_VP_EXECUTIVE_CREATIVE_DIRECTOR("VP, Executive Creative Director") ,
	COPY_VP_GROUP_EXECUTIVE_CREATIVE_DIRECTOR("VP, Group Executive Creative Director") ,
	DA_CREATIVE_DIRECTOR("Creative Director") ,
	DA_SENIOR_PRODUCER("Senior Producer") ,
	DA_SENIOR_CREATIVE_TECHNOLOGIST("Senior Creative Technologist") ,
	DA_PRODUCER("Producer") ,
	DA_CREATIVE_TECHNOLOGIST("Creative Technologist") ,
	DA_JUNIOR_VISUAL_DESIGNER("Junior Visual Designer") ,
	DA_ART_DIRECTOR("Art Director") ,
	DA_ASSOC_TECHNICAL_CREATIVE_DIRECTOR("Assoc Technical Creative Director") ,
	DA_ASSOCIATE_CREATIVE_DIRECTOR("Associate Creative Director") ,
	DA_ASSOCIATE_DESIGNER("Associate Designer") ,
	DA_ASSOCIATE_PRODUCER("Associate Producer") ,
	DA_COPYWRITER("Copywriter") ,
	DA_DIGITAL_DESIGNER("Digital Designer") ,
	DA_DIGITAL_PRODUCTION_ARTIST("Digital Production Artist") ,
	DA_EXECUTIVE_CREATIVE_DIRECTOR("Executive Creative Director") ,
	DA_EXECUTIVE_PRODUCER("Executive Producer") ,
	DA_FLASH_DESIGNER("Flash Designer") ,
	DA_GROUP_DIRECTOR_OF_DIGITAL_ADVERTISING("Group Director of Digital Advertising") ,
	DA_JUNIOR_ART_DIRECTOR("Junior Art Director") ,
	DA_JUNIOR_COPYWRITER("Junior Copywriter") ,
	DA_MANAGER_DIGITAL_PRODUCTION_ART_STUDIO("Manager, Digital Production Art Studio") ,
	DA_SENIOR_ART_DIRECTOR("Senior Art Director") ,
	DA_SENIOR_COPYWRITER("Senior Copywriter") ,
	DA_SENIOR_TECHNOLOGY_DIRECTOR("Senior Technology Director") ,
	DA_SENIOR_VISUAL_DESIGNER("Senior Visual Designer") ,
	DA_TECHNICAL_DIRECTOR_DIGITAL_ADVERTISING("Technical Director Digital Advertising") ,
	DA_TECHNOLOGY_LEAD("Technology Lead") ,
	DA_TRAFFIC_COORDINATOR("Traffic Coordinator") ,
	DA_VP_DIGITAL_ADVERTISING("VP, Digital Advertising") ,
	EXEC_EVP_CHIEF_CREATIVE_OFFICER_US("EVP, Chief Creative Officer, US") ,
	EXEC_EVP_CHIEF_TECHNOLOGY_OFFICER_US("EVP, Chief Technology Officer, US") ,
	EXEC_EVP_EXECUTIVE_CREATIVE_DIRECTOR("EVP, Executive Creative Director") ,
	EXEC_EVP_EXECUTIVE_CREATIVE_DIRECTOR_US("EVP, Executive Creative Director, US") ,
	EXEC_EVP_GLOBAL_CHIEF_DESIGN_AND_INNOVATION_OFFICER("EVP, Global Chief Design and Innovation Officer") ,
	EXEC_EVP_GLOBAL_CHIEF_EXPERIENCE_OFFICER("EVP, Global Chief Experience Officer") ,
	EXEC_EVP_GLOBAL_CHIEF_OPERATING_OFFICER ("EVP, Global Chief Operating Officer+") ,
	EXEC_EVP_GLOBAL_CHIEF_TECH_OFFICER("EVP, Global Chief Tech Officer") ,
	EXEC_EVP_MANAGING_DIRECTOR("EVP, Managing Director") ,
	EXEC_GENERAL_MANAGER("General Manager") ,
	EXEC_GLOBAL_CHIEF_CREATIVE_OFFICER("Global Chief Creative Officer") ,
	EXEC_MANAGING_DIRECTOR("Managing Director") ,
	EXEC_MANAGING_DIRECTOR_CONNECTED_SPACES("Managing Director, Connected Spaces") ,
	EXEC_MANAGING_DIRECTOR_HUSTLE("Managing Director, Hustle") ,
	EXEC_MANAGING_DIRECTOR_MARKETING_INNOVATION("Managing Director, Marketing Innovation") ,
	EXEC_MANAGING_DIRECTOR_SINGAPORE("Managing Director, Singapore") ,
	EXEC_SVP_EXECUTIVE_DIRECTOR_BRAND__MARKETING_STRATEGY("SVP Executive Director, Brand & Marketing Strategy") ,
	EXEC_SVP_CLIENT_SERVICES_US("SVP, Client Services, US") ,
	EXEC_SVP_EXECUTIVE_CREATIVE_DIRECTOR("SVP, Executive Creative Director") ,
	EXEC_SVP_GLOBAL_CREATIVE_INTEGRATION("SVP, Global Creative Integration") ,
	EXEC_SVP_GROUP_MANAGING_DIRECTOR("SVP, Group Managing Director") ,
	EXEC_SVP_MANAGING_DIRECTOR_BRAZIL("SVP, Managing Director, Brazil") ,
	EXEC_SVP_STRATEGY("SVP, Strategy") ,
	EXEC_SVP_STRATEGY_US("SVP, Strategy, US") ,
	EXEC_VICE_CHAIRMAN_GLOBAL_CHIEF_CREATIVE_OFFICER("Vice Chairman, Global Chief Creative Officer") ,
	EXEC_VP_EXECUTIVE_CREATIVE_DIRECTOR("VP, Executive Creative Director") ,
	EXEC_VP_GROUP_MANAGING_DIRECTOR("VP, Group Managing Director") ,
	EXEC_VP_MANAGING_DIRECTOR("VP, Managing Director") ,
	EXEC_VP_MANAGING_DIRECTOR_AUSTIN("VP, Managing Director, Austin") ,
	EXEC_VP_MANAGING_DIRECTOR_BRAZIL("VP, Managing Director, Brazil") ,
	EXEC_VP_MANAGING_DIRECTOR_CHICAGO("VP, Managing Director, Chicago") ,
	EXEC_VP_MANAGING_DIRECTOR_STOCKHOLM("VP, Managing Director, Stockholm") ,
	EXEC_VP_MD_INSIGHTS__PLANNING("VP, MD, Insights & Planning") ,
	EXEC_VP_TECHNOLOGY_AND_PRODUCTION("VP, Technology and Production") ,
	XD_EXPERIENCE_DESIGN_DIRECTOR("Experience Design Director") ,
	XD_SENIOR_EXPERIENCE_DESIGNER("Senior Experience Designer") ,
	XD_APPRENTICE_EXPERIENCE_DESIGN("Apprentice, Experience Design") ,
	XD_ASSOCIATE_CREATIVE_DIRECTOR("Associate Creative Director") ,
	XD_ASSOCIATE_CREATIVE_DIRECTOR_EXPERIENCE_STRATEGY("Associate Creative Director, Experience Strategy") ,
	XD_ASSOCIATE_DIRECTOR_OF_RESEARCH_FUTUREVISION("Associate Director of Research, Futurevision") ,
	XD_ASSOCIATE_DIRECTOR_CONTENT_STRATEGY("Associate Director, Content Strategy") ,
	XD_ASSOCIATE_EXPERIENCE_DESIGNER("Associate Experience Designer") ,
	XD_CREATIVE_DIRECTOR("Creative Director") ,
	XD_CREATIVE_DIRECTOR_EXPERIENCE_STRATEGY("Creative Director, Experience Strategy") ,
	XD_EXECUTIVE_CREATIVE_DIRECTOR("Executive Creative Director") ,
	XD_EXECUTIVE_CREATIVE_DIRECTOR_EXPERIENCE_STRATEGY("Executive Creative Director, Experience Strategy") ,
	XD_EXPERIENCE_DESIGNER("Experience Designer") ,
	XD_EXPERIENCE_STRATEGIST("Experience Strategist") ,
	XD_EXPERIENCE_STRATEGY_DIRECTOR("Experience Strategy Director") ,
	XD_GROUP_CREATIVE_DIRECTOR("Group Creative Director") ,
	XD_GROUP_EXECUTIVE_CREATIVE_DIRECTOR("Group Executive Creative Director") ,
	XD_INTERN_XD("Intern, XD") ,
	XD_SENIOR_EXPERIENCE_STRATEGIST("Senior Experience Strategist") ,
	XD_VP_EXECUTIVE_CREATIVE_DIRECTOR("VP, Executive Creative Director") ,
	XD_VP_MANAGING_DIRECTOR_EXECUTIVE_CREATIVE_DIRECTOR("VP, Managing Director, Executive Creative Director") ,
	XD_GLOBAL_CREATIVE_DIRECTOR("Global Creative Director") ,
	XD_REGIONAL_EXECUTIVE_CREATIVE_DIRECTOR("Regional Executive Creative Director") ,
	Finance_ASSOCIATE_DIRECTOR_MEDIA_FINANCE("Associate Director, Media Finance") ,
	Finance_CLIENT_FINANCE_ANALYST("Client Finance Analyst") ,
	Finance_JUNIOR_FINANCE_ANALYST("Junior Finance Analyst") ,
	Finance_SENIOR_CLIENT_FINANCE_ANALYST("Senior Client Finance Analyst") ,
	MS_DIRECTOR_ANALYTICS("Director, Analytics") ,
	MS_DIRECTOR_INTEGRATED_STUDIOS("Director, Integrated Studios") ,
	MS_DATA_ARCHITECT("Data Architect") ,
	MS_SENIOR_ANALYST("Senior Analyst") ,
	MS_ANALYST("Analyst") ,
	MS_DATA_SCIENTIST("Data Scientist") ,
	MS_JUNIOR_ANALYST("Junior Analyst") ,
	MS_APPRENTICE_MARKETING_SCIENCES("Apprentice, Marketing Sciences") ,
	MS_ASSOCIATE_DIRECTOR("Associate Director") ,
	MS_ASSOCIATE_DIRECTOR_ANALYTICS("Associate Director, Analytics") ,
	MS_ASSOCIATE_DIRECTOR_MARKETING_SCIENCES("Associate Director, Marketing Sciences") ,
	MS_DIRECTOR_MARKETING_SCIENCES("Director, Marketing Sciences") ,
	MS_EXECUTIVE_DIRECTOR_MARKETING_SCIENCES("Executive Director, Marketing Sciences") ,
	MS_GROUP_DIRECTOR_ANALYTICS("Group Director, Analytics") ,
	MS_GROUP_DIRECTOR_ANALYTICS_PLATFORMS_AND_INNOVATION("Group Director, Analytics Platforms and Innovation") ,
	MS_GROUP_DIRECTOR_MARKETING_SCIENCES("Group Director, Marketing Sciences") ,
	MS_INTERN_ANALYTICS("Intern, Analytics") ,
	MS_INTERN_MARKETING_SCIENCES("Intern, Marketing Sciences") ,
	MS_MANAGER_ANALYTICS("Manager, Analytics") ,
	MS_MANAGER_MARKETING_SCIENCES("Manager, Marketing Sciences") ,
	MS_MANAGING_DIRECTOR_ANALYTICS("Managing Director, Analytics") ,
	MS_MANAGING_DIRECTOR_MARKETING_SCIENCES_US("Managing Director, Marketing Sciences, US") ,
	MS_SENIOR_MANAGER_ANALYTICS("Senior Manager, Analytics") ,
	MS_SENIOR_MANAGER_MARKETING_SCIENCES("Senior Manager, Marketing Sciences") ,
	MS_SVP_MANAGING_DIRECTOR_ANALYTICS__ACCOUNTABILITY("SVP, Managing Director, Analytics & Accountability") ,
	MS_HEAD_OF_DATA("Head of Data") ,
	Media_MEDIA_DIRECTOR("Media Director") ,
	Media_SENIOR_MANAGER("Senior Manager") ,
	Media_BID_MANAGER("Bid Manager") ,
	Media_BID_ANALYST("Bid Analyst") ,
	Media_AD_OPERATIONS_ASSOCIATE("Ad Operations Associate") ,
	Media_AD_OPERATIONS_MANAGER("Ad Operations Manager") ,
	Media_ALGORITHM_ENGINEER("Algorithm Engineer") ,
	Media_APPRENTICE_MEDIA("Apprentice, Media") ,
	Media_ASSISTANT_MEDIA_PLANNER_BUYER("Assistant Media Planner/Buyer") ,
	Media_ASSOCIATE_DIRECTOR_BID_MANAGEMENT("Associate Director, Bid Management") ,
	Media_ASSOCIATE_DIRECTOR_CONNECTED_MEDIA_LAB("Associate Director, Connected Media Lab") ,
	Media_ASSOCIATE_DIRECTOR_CONNECTIONS("Associate Director, Connections") ,
	Media_ASSOCIATE_DIRECTOR_MEDIA__CONNECTIONS("Associate Director, Media & Connections") ,
	Media_ASSOCIATE_DIRECTOR_MEDIA_OPERATIONS("Associate Director, Media Operations") ,
	Media_ASSOCIATE_DIRECTOR_SEARCH("Associate Director, Search") ,
	Media_ASSOCIATE_PRODUCER("Associate Producer") ,
	Media_ASSOCIATE_SEARCH_STRATEGIST("Associate Search Strategist") ,
	Media_ASSOCIATE_BID_MANAGEMENT("Associate, Bid Management") ,
	Media_CONNECTIONS_ANALYST("Connections Analyst") ,
	Media_CONNECTIONS_PLANNER("Connections Planner") ,
	Media_CONSULTANT("Consultant") ,
	Media_DIRECTOR_BID_MANAGEMENT("Director, Bid Management") ,
	Media_DIRECTOR_CONNECTED_MEDIA_LAB("Director, Connected Media Lab") ,
	Media_DIRECTOR_CONNECTIONS("Director, Connections") ,
	Media_DIRECTOR_FINDABILITY_AND_SEO("Director, Findability and SEO") ,
	Media_DIRECTOR_MEDIA_OPERATIONS("Director, Media Operations") ,
	Media_ENGINEERING_MANAGER_CONNECTED_MEDIA_LAB("Engineering Manager, Connected Media Lab") ,
	Media_EXECUTIVE_PRODUCER("Executive Producer") ,
	Media_GROUP_DIRECTOR_CONNECTED_MEDIA_LAB("Group Director, Connected Media Lab") ,
	Media_GROUP_DIRECTOR_CONNECTIONS("Group Director, Connections") ,
	Media_GROUP_DIRECTOR_MEDIA("Group Director, Media") ,
	Media_GROUP_DIRECTOR_MEDIA_MANAGEMENT("Group Director, Media Management") ,
	Media_GROUP_MEDIA_DIRECTOR("Group Media Director") ,
	Media_INTERN_MEDIA("Intern, Media") ,
	Media_MANAGING_DIRECTOR_MEDIA_AND_CONNECTIONS("Managing Director, Media and Connections") ,
	Media_MEDIA_PLANNER_BUYER("Media Planner/Buyer") ,
	Media_MEDIA_PRODUCER("Media Producer") ,
	Media_MEDIA_PRODUCTION_DIRECTOR("Media Production Director") ,
	Media_MEDIA_SUPERVISOR("Media Supervisor") ,
	Media_PRODUCER("Producer") ,
	Media_SEARCH_STRATEGIST("Search Strategist") ,
	Media_SENIOR_ALGORITHM_ENGINEER("Senior Algorithm Engineer") ,
	Media_SENIOR_ASSOCIATE_MEDIA_OPERATIONS("Senior Associate, Media Operations") ,
	Media_SENIOR_BID_ANALYST("Senior Bid Analyst") ,
	Media_SENIOR_BID_MANAGER("Senior Bid Manager") ,
	Media_SENIOR_CONNECTIONS_PLANNER("Senior Connections Planner") ,
	Media_SENIOR_CONSULTANT("Senior Consultant") ,
	Media_SENIOR_MEDIA_PLANNER("Senior Media Planner") ,
	Media_SENIOR_SEARCH_STRATEGIST("Senior Search Strategist") ,
	Media_SVP_MEDIA_AND_CONNECTIONS("SVP, Media and Connections") ,
	Media_VP_MANAGING_DIRECTOR("VP, Managing Director") ,
	Media_VP_MEDIA_AND_CONNECTIONS("VP, Media and Connections") ,
	Media_ASSOCIATE_MEDIA_DIRECTOR("Associate Media Director") ,
	Media_SENIOR_MACHINE_LEARNING_ENGINEER("Senior Machine Learning Engineer") ,
	Media_SUPERVISOR_PAID_SEARCH("Supervisor, Paid Search") ,
	New_Business_Development_BUSINESS_DEVELOPMENT_MANAGER("Business Development Manager") ,
	Office_Services_ASSOCIATE_DIRECTOR_CREATIVE_OPERATIONS("Associate Director, Creative Operations") ,
	Office_Services_GLOBAL_PROJECTS_ARCHIVIST("Global Projects Archivist") ,
	Office_Services_PRODUCTION_ASSISTANT("Production Assistant") ,
	Presentation_ASSOCIATE_CREATIVE_DIRECTOR("Associate Creative Director") ,
	Presentation_ASSOCIATE_DESIGNER("Associate Designer") ,
	Presentation_CREATIVE_DIRECTOR("Creative Director") ,
	Presentation_DESIGNER("Designer") ,
	Presentation_DIRECTOR_PRESENTATIONS("Director, Presentations") ,
	Presentation_PRODUCER("Producer") ,
	Presentation_SENIOR_DESIGNER("Senior Designer") ,
	Presentation_SENIOR_PRESENTATION_DESIGNER("Senior Presentation Designer") ,
	PROD_GROUP_DIRECTOR_PRODUCTION("Group Director, Production") ,
	PROD_EXECUTIVE_PRODUCTION_DIRECTOR("Executive Production Director") ,
	PROD_EXECUTIVE_PRODUCER("Executive Producer") ,
	PROD_SENIOR_PRODUCER("Senior Producer") ,
	PROD_PRODUCER("Producer") ,
	PROD_ASSOCIATE_PRODUCER("Associate Producer") ,
	PROD_PRODUCTION_COORDINATOR("Production Coordinator") ,
	PROD_ACCOUNT_OPERATIONS_LEAD("Account Operations Lead") ,
	PROD_APPRENTICE_PRODUCTION("Apprentice, Production") ,
	PROD_INTERN_PRODUCTION("Intern, Production") ,
	PROD_MANAGING_DIRECTOR_PRODUCTION("Managing Director, Production") ,
	PROD_REGIONAL_EXECUTIVE_OPERATIONS_DIRECTOR("Regional Executive Operations Director") ,
	PROD_VP_EXECUTIVE_PRODUCTION_DIRECTOR("VP, Executive Production Director") ,
	PROD_DIRECTOR_PRODUCTION_OPERATIONS ("Director, Production Operations+") ,
	PROD_EXECUTIVE_PRODUCTION_DIRECTOR_CAMPAIGNS("Executive Production Director, Campaigns") ,
	PROD_PRODUCT_MANAGER("Product Manager") ,
	Prototype_Studio_APPRENTICE_PROTOTYPE_STUDIO("Apprentice, Prototype Studio") ,
	Prototype_Studio_ASSOCIATE_PRODUCER("Associate Producer") ,
	Prototype_Studio_CREATIVE_DIRECTOR_PROTOTYPE_STUDIO("Creative Director, Prototype Studio") ,
	Prototype_Studio_CREATIVE_TECHNOLOGIST("Creative Technologist") ,
	Prototype_Studio_CREATIVE_TECHNOLOGY_DIRECTOR("Creative Technology Director") ,
	Prototype_Studio_DIRECTOR_PROTOTYPE_STUDIO("Director, Prototype Studio") ,
	Prototype_Studio_EXECUTIVE_PRODUCER("Executive Producer") ,
	Prototype_Studio_EXPERIENCE_DESIGN_DIRECTOR("Experience Design Director") ,
	Prototype_Studio_INTERN_PROTOTYPE_STUDIO("Intern, Prototype Studio") ,
	Prototype_Studio_LEAD_ARCHITECT("Lead Architect") ,
	Prototype_Studio_PRODUCER("Producer") ,
	Prototype_Studio_SENIOR_EXPERIENCE_DESIGNER("Senior Experience Designer") ,
	Prototype_Studio_SENIOR_OPEN_STANDARDS_DEVELOPER("Senior Open Standards Developer") ,
	Prototype_Studio_SENIOR_PRODUCER("Senior Producer") ,
	Prototype_Studio_SENIOR_SOFTWARE_ENGINEER_PROTOTYPE_STUDIO("Senior Software Engineer, Prototype Studio") ,
	Prototype_Studio_SENIOR_TECHNOLOGY_DIRECTOR_PROTOTYPE_STUDIO("Senior Technology Director, Prototype Studio") ,
	Prototype_Studio_SOFTWARE_ENGINEER("Software Engineer") ,
	Prototype_Studio_TECHNOLOGY_LEAD("Technology Lead") ,
	QA_TECHNOLOGY_LEAD_QUALITY_ASSURANCE("Technology Lead, Quality Assurance") ,
	QA_SENIOR_QA_ENGINEER("Senior QA Engineer") ,
	QA_QA_ENGINEER("QA Engineer") ,
	QA_ASSOCIATE_QA_ENGINEER("Associate QA Engineer") ,
	QA_ASSOCIATE_TECHNOLOGY_DIRECTOR_QUALITY_ASSURANCE("Associate Technology Director, Quality Assurance") ,
	QA_QUALITY_ASSURANCE_ANALYST("Quality Assurance Analyst") ,
	QA_QUALITY_CONTROL_TESTER("Quality Control Tester") ,
	QA_TECHNOLOGY_DIRECTOR_QUALITY_ASSURANCE("Technology Director, Quality Assurance") ,
	QA_TESTER("Tester") ,
	QA_INTERN_QA("Intern, QA") ,
	QA_QUALITY_ASSURANCE_LEAD("Quality Assurance Lead") ,
	Resource_Management_ASSOCIATE_DIRECTOR_RESOURCE_MANAGEMENT ("Associate Director, Resource Management+") ,
	STRAT_HEAD_OF_STRATEGY_AND_PLANNING("Head of Strategy and Planning") ,
	STRAT_STRATEGY_DIRECTOR("Strategy Director") ,
	STRAT_SENIOR_STRATEGIST("Senior Strategist") ,
	STRAT_STRATEGIST("Strategist") ,
	STRAT_ASSOCIATE_STRATEGIST("Associate Strategist") ,
	STRAT_COMMUNITY_MANAGER("Community Manager") ,
	STRAT_ANALYST("Analyst") ,
	STRAT_APPRENTICE_EXPERIENCE_STRATEGY("Apprentice, Experience Strategy") ,
	STRAT_APPRENTICE_STRATEGY("Apprentice, Strategy") ,
	STRAT_ASSOCIATE_EXPERIENCE_STRATEGIST("Associate Experience Strategist") ,
	STRAT_ASSOCIATE_PLANNING_DIRECTOR("Associate Planning Director") ,
	STRAT_ASSOCIATE_PLANNING_DIRECTOR_CONTENT("Associate Planning Director, Content") ,
	STRAT_ASSOCIATE_STRATEGY_DIRECTOR("Associate Strategy Director") ,
	STRAT_CONTENT_STRATEGIST("Content Strategist") ,
	STRAT_DIGITAL_STRATEGIST("Digital Strategist") ,
	STRAT_DIRECTOR_OF_EXPERIENCE_STRATEGY("Director of Experience Strategy") ,
	STRAT_EDITORIAL_DIRECTOR("Editorial Director") ,
	STRAT_EXECUTIVE_STRATEGY_DIRECTOR("Executive Strategy Director") ,
	STRAT_EXPERIENCE_STRATEGIST("Experience Strategist") ,
	STRAT_GROUP_DIRECTOR_BRAND_STRATEGY("Group Director, Brand Strategy") ,
	STRAT_GROUP_DIRECTOR_PLANNING("Group Director, Planning") ,
	STRAT_GROUP_DIRECTOR_STRATEGY("Group Director, Strategy") ,
	STRAT_GROUP_PLANNING_LEAD("Group Planning Lead") ,
	STRAT_GROUP_STRATEGY_DIRECTOR("Group Strategy Director") ,
	STRAT_GROUP_STRATEGY_LEAD("Group Strategy Lead") ,
	STRAT_HEAD_OF_PLANNING("Head of Planning") ,
	STRAT_INTERN_EXPERIENCE_STRATEGY("Intern, Experience Strategy") ,
	STRAT_INTERN_RESEARCH_PLANNING("Intern, Research/Planning") ,
	STRAT_JUNIOR_PLANNER("Junior Planner") ,
	STRAT_MANAGER_SOCIAL("Manager, Social") ,
	STRAT_MANAGING_DIRECTOR_INSIGHTS__PLANNING("Managing Director, Insights & Planning") ,
	STRAT_MANAGING_DIRECTOR_PLANNING("Managing Director, Planning") ,
	STRAT_MANAGING_DIRECTOR_SOCIAL("Managing Director, Social") ,
	STRAT_MANAGING_DIRECTOR_STRATEGY("Managing Director, Strategy") ,
	STRAT_PLANNER("Planner") ,
	STRAT_PLANNING_DIRECTOR("Planning Director") ,
	STRAT_REGIONAL_MANAGING_DIRECTOR_STRATEGY("Regional Managing Director Strategy") ,
	STRAT_REGIONAL_PLANNING_DIRECTOR("Regional Planning Director") ,
	STRAT_REGIONAL_STRATEGY_DIRECTOR("Regional Strategy Director") ,
	STRAT_RESEARCH_DIRECTOR("Research Director") ,
	STRAT_SENIOR_CONTENT_STRATEGIST("Senior Content Strategist") ,
	STRAT_SENIOR_EXPERIENCE_PLANNER("Senior Experience Planner") ,
	STRAT_SENIOR_EXPERIENCE_STRATEGIST("Senior Experience Strategist") ,
	STRAT_SENIOR_PLANNER("Senior Planner") ,
	STRAT_SENIOR_SOCIAL_STRATEGIST("Senior Social Strategist") ,
	STRAT_SOCIAL_STRATEGIST("Social Strategist") ,
	STRAT_SVP_MANAGING_DIRECTOR_INSIGHTS("SVP, Managing Director, Insights") ,
	STRAT_VP_CONTENT_AND_PARTNERSHIPS("VP, Content and Partnerships") ,
	STRAT_VP_EXECUTIVE_STRATEGY_DIRECTOR("VP, Executive Strategy Director") ,
	STRAT_VP_MANAGING_DIRECTOR_INSIGHTS("VP, Managing Director, Insights") ,
	STRAT_VP_STRATEGY_DIRECTOR("VP, Strategy Director") ,
	STRAT_RESEARCHER("Researcher") ,
	STRAT_SVP_STRATEGY_US("SVP, Strategy, US") ,
	TECH_EXECUTIVE_TECHNOLOGY_DIRECTOR("Executive Technology Director") ,
	TECH_SENIOR_TECHNOLOGY_DIRECTOR("Senior Technology Director") ,
	TECH_TECHNOLOGY_DIRECTOR("Technology Director") ,
	TECH_ASSOCIATE_ENGINEERING_DIRECTOR_MOBILE_PLATFORMS("Associate Engineering Director, Mobile Platforms") ,
	TECH_ASSOCIATE_TECHNOLOGY_DIRECTOR("Associate Technology Director") ,
	TECH_LEAD_ENGINEER_APPLIED_SCIENCES("Lead Engineer, Applied Sciences") ,
	TECH_TECHNOLOGY_LEAD("Technology Lead") ,
	TECH_SENIOR_SOFTWARE_ENGINEER_MOBILE_PLATFORMS("Senior Software Engineer, Mobile Platforms") ,
	TECH_SENIOR_SOFTWARE_ENGINEER("Senior Software Engineer") ,
	TECH_SENIOR_SOFTWARE_ENGINEER_WEB_PLATFORMS("Senior Software Engineer, Web Platforms") ,
	TECH_SOFTWARE_ENGINEER_MOBILE_PLATFORMS("Software Engineer, Mobile Platforms") ,
	TECH_SENIOR_PRESENTATION_CODE_DEVELOPER("Senior Presentation Code Developer") ,
	TECH_SOFTWARE_ENGINEER_WEB_PLATFORMS("Software Engineer, Web Platforms") ,
	TECH_PRESENTATION_CODE_DEVELOPER("Presentation Code Developer") ,
	TECH_APPRENTICE_TECHNOLOGY("Apprentice, Technology") ,
	TECH_ASSOCIATE_DATA_SCIENTIST("Associate Data Scientist") ,
	TECH_ASSOCIATE_ENGINEERING_DIRECTOR("Associate Engineering Director") ,
	TECH_ASSOCIATE_SOFTWARE_ENGINEER("Associate Software Engineer") ,
	TECH_ASSOCIATE_SOFTWARE_ENGINEER_MOBILE_PLATFORMS("Associate Software Engineer, Mobile Platforms") ,
	TECH_ASSOCIATE_SOFTWARE_ENGINEER_WEB_PLATFORMS("Associate Software Engineer, Web Platforms") ,
	TECH_ASSOCIATE_TECHNICAL_CREATIVE_DIRECTOR("Associate Technical Creative Director") ,
	TECH_ASSOCIATE_TECHNICAL_DIRECTOR("Associate Technical Director") ,
	TECH_BUSINESS_SYSTEMS_ANALYST("Business Systems Analyst") ,
	TECH_CREATIVE_TECHNOLOGY_DIRECTOR("Creative Technology Director") ,
	TECH_DATA_SCIENTIST("Data Scientist") ,
	TECH_DIRECTOR_CONNECTED_SPACES_IT_AV_DESIGN("Director, Connected Spaces IT/AV Design") ,
	TECH_DIRECTOR_SOFTWARE_PLATFORM_LAB_PARTNERSHIPS("Director, Software Platform Lab Partnerships") ,
	TECH_EXECUTIVE_CREATIVE_DIRECTOR("Executive Creative Director") ,
	TECH_FLASH_DEVELOPER("Flash Developer") ,
	TECH_GROUP_TECHNOLOGY_DIRECTOR("Group Technology Director") ,
	TECH_INTERN_TECHNOLOGY("Intern, Technology") ,
	TECH_JR_OPEN_STANDARDS_DEVELOPER("Jr. Open Standards Developer") ,
	TECH_JR_PRESENTATION_CODE_DEVELOPER("Jr. Presentation Code Developer") ,
	TECH_JUNIOR_SOFTWARE_ENGINEER("Junior Software Engineer") ,
	TECH_LEAD_ARCHITECT("Lead Architect") ,
	TECH_LEAD_ENGINEER_MOBILE_PLATFORMS("Lead Engineer, Mobile Platforms") ,
	TECH_OPEN_STANDARDS_DEVELOPER("Open Standards Developer") ,
	TECH_PARTNERSHIPS_ASSOCIATE_SPL("Partnerships Associate, SPL") ,
	TECH_SENIOR_BUSINESS_SYSTEMS_ANALYST("Senior Business Systems Analyst") ,
	TECH_SENIOR_OPEN_STANDARDS_DEVELOPER("Senior Open Standards Developer") ,
	TECH_SENIOR_SOFTWARE_ENGINEER_TEST_AUTOMATION("Senior Software Engineer, Test Automation") ,
	TECH_SENIOR_TECHNICAL_ARCHITECT("Senior Technical Architect") ,
	TECH_SENIOR_TECHNOLOGY_DIRECTOR_MOBILE_PLATFORMS("Senior Technology Director, Mobile Platforms") ,
	TECH_SOFTWARE_ENGINEER("Software Engineer") ,
	TECH_SVP_TECHNOLOGY("SVP, Technology") ,
	TECH_TECHNICAL_CREATIVE_DIRECTOR("Technical Creative Director") ,
	TECH_TECHNICAL_DIRECTOR("Technical Director") ,
	TECH_TECHNICAL_DIRECTOR__SOLUTIONS_ARCHITECT("Technical Director & Solutions Architect") ,
	TECH_TECHNICAL_TEAM_LEADER("Technical Team Leader") ,
	TECH_TECHNOLOGY_ANALYST_BUSINESS_TRANSFORMATION("Technology Analyst, Business Transformation") ,
	TECH_TECHNOLOGY_DIRECTOR_INTERNAL_PLATFORMS("Technology Director, Internal Platforms") ,
	TECH_TECHNOLOGY_DIRECTOR_PROGRAM_MANAGEMENT("Technology Director, Program Management") ,
	TECH_TECHNOLOGY_PROJECT_LEADER("Technology Project Leader") ,
	TECH_VP_TECHNOLOGY("VP, Technology") ,
	TECH_VP_TECHNOLOGY_US("VP, Technology, US") ,
	TECH_CHIEF_TECHNOLOGY_OFFICER_US("Chief Technology Officer, US") ,
	TECH_DATA_SCIENCE_LEAD("Data Science Lead") ,
	TECH_FRONT_END_SOLUTIONS_ARCHITECT("Front End Solutions Architect") ,
	TECH_SENIOR_DATA_SCIENTIST("Senior Data Scientist") ,
	TECH_SENIOR_TECHNICAL_DIRECTOR("Senior Technical Director") ,
	TECH_TECH_CONSULTANT("Tech Consultant") ,
	VISUAL_VP_EXECUTIVE_CREATIVE_DIRECTOR("VP, Executive Creative Director") ,
	VISUAL_VP_EXECUTIVE_CREATIVE_DIRECTOR_SS_LATAM("VP, Executive Creative Director, SS LATAM") ,
	VISUAL_CREATIVE_DIRECTOR("Creative Director") ,
	VISUAL_DESIGN_DIRECTOR("Design Director") ,
	VISUAL_ASSOCIATE_CREATIVE_DIRECTOR("Associate Creative Director") ,
	VISUAL_SENIOR_VISUAL_DESIGNER("Senior Visual Designer") ,
	VISUAL_VISUAL_DESIGNER("Visual Designer") ,
	VISUAL_JUNIOR_VISUAL_DESIGNER("Junior Visual Designer") ,
	VISUAL_APPRENTICE_ART_DIRECTION("Apprentice, Art Direction") ,
	VISUAL_APPRENTICE_DESIGN("Apprentice, Design") ,
	VISUAL_ART_DIRECTOR("Art Director") ,
	VISUAL_ASSOCIATE_CREATIVE_DIRECTOR_DESIGN("Associate Creative Director, Design") ,
	VISUAL_ASSOCIATE_DESIGN_DIRECTOR("Associate Design Director") ,
	VISUAL_ASSOCIATE_DESIGNER("Associate Designer") ,
	VISUAL_CREATIVE_DIRECTOR_TALENT_DEVELOPMENT("Creative Director, Talent Development") ,
	VISUAL_DESIGN_DIRECTOR_2015("Design Director 2015") ,
	VISUAL_DESIGNER("Designer") ,
	VISUAL_EXECUTIVE_CREATIVE_DIRECTOR("Executive Creative Director") ,
	VISUAL_GLOBAL_EXECUTIVE_CREATIVE_DIRECTOR("Global Executive Creative Director") ,
	VISUAL_GLOBAL_EXECUTIVE_DESIGN_DIRECTOR("Global Executive Design Director") ,
	VISUAL_GROUP_CREATIVE_DIRECTOR("Group Creative Director") ,
	VISUAL_GROUP_DESIGN_DIRECTOR("Group Design Director") ,
	VISUAL_GROUP_EXECUTIVE_CREATIVE_DIRECTOR("Group Executive Creative Director") ,
	VISUAL_INTERN_DESIGN("Intern, Design") ,
	VISUAL_INTERN_VISUAL("Intern, Visual") ,
	VISUAL_JUNIOR_ART_DIRECTOR("Junior Art Director") ,
	VISUAL_MAC_OPERATOR("Mac Operator") ,
	VISUAL_REGIONAL_EXECUTIVE_CREATIVE_DIRECTOR("Regional Executive Creative Director") ,
	VISUAL_SENIOR_ART_DIRECTOR("Senior Art Director") ,
	VISUAL_SENIOR_CREATIVE_DEVELOPER("Senior Creative Developer") ,
	VISUAL_SENIOR_DESIGNER("Senior Designer") ,
	VISUAL_SVP_EXECUTIVE_CREATIVE_DIRECTOR("SVP, Executive Creative Director") ,
	VISUAL_VP_ECD_PRODUCT_INNOVATION("VP, ECD, Product Innovation") ,
	VISUAL_VP_GROUP_EXECUTIVE_CREATIVE_DIRECTOR("VP, Group Executive Creative Director") ;
	
    private String url;

    Positions(String url) {
        this.url = url;
    }

    public String url() {
        return url;
    }
}